version: "3"

services:
  mysql:
    image: mysql:5.7.16
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""
    container_name: "${DB_CONTAINER_NAME}"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      TZ: "America/Sao_Paulo"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "db_volume:${VOLUME_PATH}"
      - ./src/infra/database/configs:/docker-entrypoint-initdb.d  # OBS: Esta linha inicializa um script de criação da database de teste, localizado na ./src/infra/database/configs, o mesmo precisa ter o nome igual da variável de ambiente .env.test DB_DATABASE
    env_file:
      - .env

  test:
    build: .
    command: yarn test
    volumes:
      - .:/usr/tests

  dev:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app

volumes:
  db_volume:
    external: false
